Repository openedx/frontend-app-discussions, pull requests merged in 2022-03, with the labels that each got.

#72 [BD-38] [TNL-9573] [BB-5556] Adds an indicator to Post Links for new comments
  src/discussions/posts/post/PostFooter.jsx
  src/discussions/posts/post/PostFooter.test.jsx
  src/discussions/posts/post/messages.js
Labels: needs triage, blended

#85 [BD-38] [TNL-9611] [BB-5606] Show check icons for endorsed posts
  src/discussions/comments/comment/CommentHeader.jsx
  src/discussions/comments/comment/CommentHeader.test.jsx
Labels: needs triage, blended

#65 feat: show empty state on posts pages [BD-38] [TNL-9484] [SE-5347]
  src/assets/empty.svg
  src/discussions/data/hooks.js
  src/discussions/data/selectors.js
  src/discussions/discussions-home/DiscussionContent.jsx
  src/discussions/discussions-home/DiscussionSidebar.jsx
  src/discussions/discussions-home/DiscussionSidebar.test.jsx
  src/discussions/discussions-home/DiscussionsHome.jsx
  src/discussions/empty-posts/EmptyPage.jsx
  src/discussions/empty-posts/EmptyPosts.jsx
  src/discussions/empty-posts/EmptyPosts.test.jsx
  src/discussions/empty-posts/EmptyTopics.jsx
  src/discussions/empty-posts/EmptyTopics.test.jsx
  src/discussions/empty-posts/index.js
  src/discussions/messages.js
  src/discussions/posts/NoResults.jsx
  src/discussions/posts/NoResults.test.jsx
  src/discussions/posts/PostsView.jsx
  src/discussions/posts/index.js
  src/discussions/topics/data/__factories__/topics.factory.js
Labels: needs triage, blended

#82 fix: filtering by post type wasn't working [BD-38] [TNL-9609]
  src/data/constants.js
  src/discussions/data/selectors.js
  src/discussions/posts/PostsView.test.jsx
  src/discussions/posts/data/__factories__/threads.factory.js
  src/discussions/posts/data/api.js
  src/discussions/posts/data/redux.test.js
  src/discussions/posts/data/slices.js
  src/discussions/posts/data/thunks.js
  src/discussions/posts/post-filter-bar/PostFilterBar.jsx
  src/discussions/posts/post-filter-bar/messages.js
Labels: needs triage, blended

#93 fix: related link for posts should open in top frame [TNL-9647] [BD-38]
  src/discussions/posts/post/Post.jsx
Labels: needs triage, blended

#88 fix: clear saved post or comment on submit [BD-38] [TNL-9630]
  src/discussions/comments/CommentsView.test.jsx
  src/discussions/comments/comment/CommentEditor.jsx
  src/discussions/comments/messages.js
  src/discussions/posts/post-editor/PostEditor.jsx
Labels: needs triage, blended

#46 [BD-38] [TNL-9266] [BB-5143] Add reason code selection UI for moderators on posts
  src/discussions/comments/CommentsView.test.jsx
  src/discussions/comments/comment/Comment.jsx
  src/discussions/comments/comment/CommentEditor.jsx
  src/discussions/comments/data/api.js
  src/discussions/comments/data/redux.test.js
  src/discussions/comments/messages.js
  src/discussions/common/AlertBanner.jsx
  src/discussions/common/AlertBanner.test.jsx
  src/discussions/data/selectors.js
  src/discussions/data/slices.js
  src/discussions/navigation/breadcrumb-menu/BreadcrumbMenu.test.jsx
  src/discussions/navigation/breadcrumb-menu/LegacyBreadcrumbMenu.test.jsx
  src/discussions/posts/data/api.js
  src/discussions/posts/data/redux.test.js
  src/discussions/posts/data/thunks.js
  src/discussions/posts/post-editor/PostEditor.jsx
  src/discussions/posts/post-editor/PostEditor.test.jsx
  src/discussions/posts/post-editor/messages.js
  src/discussions/posts/post/Post.jsx
  src/discussions/posts/post/messages.js
Labels: needs triage, blended

#91 fix : [BB-5597][TNL-9618] [BD-38] text leaking out from post summary
  src/discussions/posts/post/Post.jsx
  src/discussions/posts/post/PostLink.jsx
Labels: rejected, blended

#73 fix: [BD-38] [TNL-5596][BB-5596] Fix TinyMCE padding
  src/components/TinyMCEEditor.jsx
Labels: rejected, blended

#74 fix: [BD-38] [BB-5599] [TNL-9629] fix `Follow` button on post summary
  src/discussions/posts/post/PostFooter.jsx
  src/discussions/posts/post/PostFooter.test.jsx
Labels: rejected, blended

#83 feat: [BD-38] [BB-5013] Add Learners list
  src/data/constants.js
  src/discussions/common/context.js
  src/discussions/data/hooks.js
  src/discussions/data/selectors.js
  src/discussions/data/slices.js
  src/discussions/discussions-home/DiscussionSidebar.jsx
  src/discussions/discussions-home/DiscussionsHome.jsx
  src/discussions/learners/LearnersView.jsx
  src/discussions/learners/LearnersView.test.jsx
  src/discussions/learners/data/__factories__/index.js
  src/discussions/learners/data/__factories__/learners.factory.js
  src/discussions/learners/data/api.js
  src/discussions/learners/data/index.js
  src/discussions/learners/data/selectors.js
  src/discussions/learners/data/slices.js
  src/discussions/learners/data/thunks.js
  src/discussions/learners/index.js
  src/discussions/learners/learner/LearnerAvatar.jsx
  src/discussions/learners/learner/LearnerCard.jsx
  src/discussions/learners/learner/LearnerFooter.jsx
  src/discussions/learners/learner/LearnerFooter.test.jsx
  src/discussions/learners/learner/index.js
  src/discussions/learners/learner/messages.js
  src/discussions/learners/learner/proptypes.js
  src/discussions/navigation/navigation-bar/NavigationBar.jsx
  src/discussions/navigation/navigation-bar/messages.js
  src/store.js
Labels: community manager review, blended

#94 fix: update icons to match mockups better [BD-38] [TNL-9208] [TNL-9209]
  package-lock.json
  package.json
  src/discussions/common/ActionsDropdown.jsx
  src/discussions/common/AlertBanner.jsx
  src/discussions/common/AuthorLabel.jsx
  src/discussions/messages.js
  src/discussions/posts/post/PostFooter.jsx
  src/discussions/posts/post/PostLink.jsx
  src/discussions/topics/topic-group/topic/Topic.jsx
Labels: needs triage, blended

#104 fix: update post when comment is marked as answer; reload topics on open [BD-38] [TNL-9646] [TNL-9703]
  src/discussions/comments/CommentsView.test.jsx
  src/discussions/comments/comment/Comment.jsx
  src/discussions/topics/TopicsView.jsx
Labels: needs triage, blended

#103 fix: align empty state in the center and auto-grow container [BD-38] [TNL-9684] [TNL-9627]
  src/discussions/discussions-home/DiscussionsHome.jsx
  src/discussions/empty-posts/EmptyPage.jsx
Labels: needs triage, blended

#100 feat: use postMessage API to send size hints to allow iframe to dynamically resize [BD-38] [TNL-9608] [TNL-9585]
  .env
  .env.development
  .env.test
  src/discussions/comments/CommentsView.test.jsx
  src/discussions/data/hooks.js
  src/discussions/data/hooks.test.jsx
  src/discussions/discussions-home/DiscussionContent.jsx
  src/setupTest.js
Labels: needs triage, blended
