Repository openedx/frontend-app-discussions, pull requests merged in 2023-11, with the labels that each got.

#601 fix: container indents and style imports
  src/components/NavigationBar/navBar.scss
  src/index.scss
Labels: engineering review, open-source-contribution, backport

#599 fix: container indents and style imports
  src/components/NavigationBar/navBar.scss
  src/index.scss
Labels: open-source-contribution, backport

#598 fix: unify font-family with paragon component styles
  src/discussions/common/AuthorLabel.jsx
  src/discussions/common/EndorsedAlertBanner.jsx
  src/index.scss
Labels: engineering review, waiting on author, open-source-contribution

#596 fix: unify font-family with paragon component styles
  src/discussions/common/AuthorLabel.jsx
  src/discussions/common/EndorsedAlertBanner.jsx
  src/index.scss
Labels: engineering review, open-source-contribution, backport

#600 fix: container indents and style imports
  src/components/NavigationBar/navBar.scss
  src/index.scss
Labels: engineering review, open-source-contribution

#614 fix: resolved load more posts delay issue (quince.master)
  src/discussions/posts/post/PostLink.jsx
Labels: backport
