Repository openedx/frontend-app-discussions, pull requests merged in 2023-03, with the labels that each got.

#449 fix: Fix for code block formatting on the post preview and published post view
  src/index.scss
Labels: product review, open-source-contribution

#467 fix: my posts tab search
  src/discussions/posts/PostsList.jsx
Labels: open-source-contribution, ready to merge

#455 fix: post sharing URL
  src/discussions/posts/post/Post.jsx
Labels: engineering review, open-source-contribution
